Repository woowa-techcamp-2022/web-todo-5, pull requests merged in 2022-07, with the labels that each got.

#2 프로젝트 초기 세팅 (+ 환경 변수)
  .gitignore
  .prettierrc
  babel.config.json
  client/index.js
  client/index.scss
  package.json
  server/app.js
  server/bin/www
  server/db/loader.js
  server/routes/index.js
  webpack.config.js
Labels: 설정

#18 리스트(보드) UI 작업
  client/App.js
  client/component/Board/Board.js
  client/component/Board/Board.scss
  client/component/Board/CardList.js
  client/component/Board/CardList.scss
  client/index.scss
Labels: 기능, 리뷰, 프론트엔드

#19 메뉴바 UI 작업
  client/component/Header.js
  client/component/MenuBar/History.js
  client/component/MenuBar/History.scss
  client/component/MenuBar/MenuBar.js
  client/component/MenuBar/MenuBar.scss
  client/index.scss
Labels: 기능, 리뷰, 프론트엔드

#20 카드(보드) UI 작업
  client/component/Board/CardItem.js
  client/component/Board/CardItem.scss
  client/component/Board/CardList.js
Labels: 기능, 프론트엔드

#22 히스토리 아이템 UI 작업
  client/component/MenuBar/History.js
  client/component/MenuBar/History.scss
  client/component/MenuBar/MenuBar.scss
Labels: 기능, 프론트엔드

#23 카드(보드) 정보 입력 UI 작업
  client/component/Board/CardActive.js
  client/component/Board/CardActive.scss
  client/component/Board/CardList.js
Labels: 기능, 프론트엔드

#24 히스토리 나열 작업
  client/component/MenuBar/History.js
  client/component/MenuBar/MenuBar.js
Labels: 기능, 프론트엔드

#25 카드(보드) 정보 입력 UI 작업 - DB 생성 작업
  server/app.js
  server/db/loader.js
  server/db/repository/board.js
  server/db/repository/card.js
Labels: 백엔드, 기능, 설정

#26 히스토리 나열 작업 - 히스토리 이어 붙일 때 발생하는 버그 해결
  client/component/MenuBar/History.js
Labels: 기능, 프론트엔드

#27 히스토리 API
  client/component/MenuBar/History.js
  client/component/MenuBar/api/history.js
  server/app.js
  server/db/loader.js
  server/db/repository/history.js
  server/routes/history.js
  server/routes/util.js
Labels: 백엔드, 기능, 프론트엔드

#28 카드 API
  server/app.js
  server/db/repository/card.js
  server/db/service/card.js
  server/routes/card.js
Labels: 백엔드, 기능

#30 :sparkles: 보드 전체 결과 값 가져오기 -#29
  server/app.js
  server/db/service/board.js
  server/routes/board.js
Labels: 백엔드, 기능

#32 리스트와 카드 데이터 받아와 나열하기
  client/api/board.js
  client/api/history.js
  client/component/Board/Board.js
  client/component/Board/CardItem.js
  client/component/Board/CardList.js
  client/component/Board/CardList.scss
  client/component/MenuBar/History.js
  server/db/service/board.js
Labels: 기능, 프론트엔드

#33 카드 Drag and Drop 기능
  client/component/Board/CardItem.scss
  client/component/Board/CardList.js
  client/component/Board/CardList.scss
  client/component/Board/dragAndDrop.js
  client/index.scss
Labels: 기능, 프론트엔드

#35 카드 CRUD API - 히스토리 API 연결
  client/api/card.js
  client/component/MenuBar/MenuBar.scss
  server/db/service/history.js
Labels: 기능, 프론트엔드

#36 카드 삭제를 클릭 이벤트에서 발생
  client/api/card.js
  client/component/Board/CardItem.js
  client/component/Board/CardItem.scss
  client/component/Board/CardList.js
Labels: 백엔드, 기능, 프론트엔드

#38 카드 등록 기능 추가
  client/api/card.js
  client/component/Board/CardActive.js
  client/component/Board/CardList.js
Labels: 기능, 프론트엔드

#39 README.md 를 위한 배포
  client/image/favicon.ico
  client/index.js
  readme.md
  webpack.config.js
Labels: 문서
